apiVersion: v1
kind: Service
metadata:
  name: mini-credit-service
  labels:
    app: mini-credit-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: mini-credit-service 